version: "3.7"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
      
  mongodb:
    image : mongo
    ports : 
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express
    ports:
        - 8080:8081
    environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
        - ME_CONFIG_BASICAUTH=false
volumes:
  mongodb-data:
    driver: local