name: Java CI with ESLint, Docker, Trivy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - ps-nana-js-docker-repo/techworld-js-docker-demo-app/**

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: techworld-js-docker-demo-app
    strategy:
      matrix:
        node-version: [14, 16, 18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: ESLint installation
        run: npm init @eslint/config@latest

      - name: Run ESLint test
        run: npx eslint yourfile.js

      - name: run auditjs
        run: |
          npx auditjs@beta ossi

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.61.0

      - name: Scan Docker image with Trivy
        run: |
          docker build -t java-login-app:latest .
          trivy image --exit-code=0 --severity HIGH,CRITICAL java-login-app:latest
          working-directory: DevOps-Project-01/Java-Login-App

      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker image
        run: |
          docker tag java-login-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/java-login-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/java-login-app:latest