name: Java CI with ESLint, Docker, Trivy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    
    strategy:
      matrix:
        node-version: [18]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Install ESLint
        run: npm install --save-dev eslint

      - name: Run ESLint test
        run: npx eslint .
        continue-on-error: true

      - name: run auditjs
        run: |
          npx auditjs@beta ossi
        continue-on-error: true

      - name: Install Trivy
        uses: aquasecurity/setup-trivy@v0.2.3
        with:
          version: v0.61.0

      - name: Scan Docker image with Trivy
        working-directory: techworld-js-docker-demo-app
        run: |
          docker build -t ps-nana-js:latest .
          trivy image --exit-code=0 --severity HIGH,CRITICAL ps-nana-js:latest


      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: push docker image
        run: |
          docker tag ps-nana-js:latest ${{ secrets.DOCKERHUB_USERNAME }}/ps-nana-js:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/ps-nana-js:latest